# Generated by Django 3.0.3 on 2020-03-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'manager--资讯文章表', 'verbose_name_plural': 'manager--资讯文章表'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='manager--资讯文章表',
        ),
    ]
