# Generated by Django 3.0.3 on 2020-03-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0016_auto_20200313_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='问题标题')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='问题内容')),
                ('answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='回答内容')),
                ('homework_status', models.IntegerField(choices=[(1, '未回答'), (2, '已回答')], default=1, verbose_name='问题回答状态')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_stu', to='rbac.UserInfo', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_tea', to='rbac.UserInfo', verbose_name='导师')),
            ],
            options={
                'verbose_name': '学生-问题表',
                'verbose_name_plural': '学生-问题表',
                'db_table': '学生-问题表',
            },
        ),
    ]
