# Generated by Django 3.0.3 on 2020-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='homework_status',
            new_name='question_status',
        ),
    ]
