# Generated by Django 3.0.3 on 2020-03-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('student', '0002_auto_20200314_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='课程的分类')),
            ],
            options={
                'verbose_name': 'student-课程分类表',
                'verbose_name_plural': 'student-课程分类表',
                'db_table': 'student-课程分类表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='课程的名称')),
                ('course_img', models.ImageField(upload_to='course/%Y-%m', verbose_name='课程的图片')),
                ('course_type', models.SmallIntegerField(choices=[(0, '付费'), (1, 'vip专享'), (2, '学位课程')])),
                ('brief', models.CharField(max_length=1024, verbose_name='课程简介')),
                ('status', models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0)),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('order', models.IntegerField(help_text='从上一个课程数字往后排', verbose_name='课程顺序')),
                ('study_num', models.IntegerField(help_text='只要有人买课程，订单表加入数据的同时给这个字段+1', verbose_name='学习人数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Category', verbose_name='课程的分类')),
            ],
            options={
                'verbose_name': 'student-课程表',
                'verbose_name_plural': 'student-课程表',
                'db_table': 'student-课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.SmallIntegerField(default=1, verbose_name='第几章')),
                ('title', models.CharField(max_length=32, verbose_name='课程章节名称')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='student.Course')),
            ],
            options={
                'verbose_name': 'student-课程章节表',
                'verbose_name_plural': 'student-课程章节表',
                'db_table': 'student-课程章节表',
                'unique_together': {('course', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='DegreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='学位课程名字')),
            ],
            options={
                'verbose_name': 'student-学位课程表',
                'verbose_name_plural': 'student-学位课程表',
                'db_table': 'student-学位课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=7, verbose_name='课时')),
                ('video_brief_link', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(max_length=2048, verbose_name='课程概述')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
                ('recommend_courses', models.ManyToManyField(blank=True, related_name='recommend_by', to='student.Course')),
            ],
            options={
                'verbose_name': 'student-课程详细表',
                'verbose_name_plural': 'student-课程详细表',
                'db_table': 'student-课程详细表',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='degree_course',
            field=models.ForeignKey(blank=True, help_text='如果是学位课程，必须关联学位表', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.DegreeCourse'),
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('valid_period', models.SmallIntegerField(choices=[(1, '1天'), (3, '3天'), (7, '1周'), (14, '2周'), (30, '1个月'), (60, '2个月'), (90, '3个月'), (120, '4个月'), (180, '6个月'), (210, '12个月'), (540, '18个月'), (720, '24个月'), (722, '24个月'), (723, '24个月')])),
                ('price', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'student-价格策略表',
                'verbose_name_plural': 'student-价格策略表',
                'db_table': 'student-价格策略表',
                'unique_together': {('content_type', 'object_id', 'valid_period')},
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课时')),
                ('section_order', models.SmallIntegerField(help_text='建议每个课时之间空1至2个值，以备后续插入课时', verbose_name='课时排序')),
                ('free_trail', models.BooleanField(default=False, verbose_name='是否可试看')),
                ('section_type', models.SmallIntegerField(choices=[(0, '文档'), (1, '练习'), (2, '视频')], default=2)),
                ('section_link', models.CharField(blank=True, help_text='若是video，填vid,若是文档，填link', max_length=255, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='student.CourseChapter')),
            ],
            options={
                'verbose_name': 'student-课程课时表',
                'verbose_name_plural': 'student-课程课时表',
                'db_table': 'student-课程课时表',
                'unique_together': {('chapter', 'section_link')},
            },
        ),
    ]
