# Generated by Django 3.0.3 on 2020-03-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_auto_20200313_1232'),
        ('student', '0003_auto_20200315_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course', verbose_name='购物车课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='rbac.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'student-购物车表',
                'verbose_name_plural': 'student-购物车表',
                'db_table': 'student-购物车表',
            },
        ),
    ]
