# Generated by Django 3.0.3 on 2020-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200315_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='price_policy',
            field=models.IntegerField(blank=True, null=True, verbose_name='选择的价格方案'),
        ),
    ]
