# Generated by Django 3.0.3 on 2020-03-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_shoppingcart_price_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
