# Generated by Django 3.0.3 on 2020-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200317_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='amount',
            field=models.FloatField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='balance',
            field=models.FloatField(verbose_name='账户余额'),
        ),
    ]
