# Generated by Django 3.0.3 on 2020-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_auto_20200320_1132'),
        ('student', '0010_auto_20200320_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', verbose_name='用户')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Course', verbose_name='购买学习的课程')),
            ],
        ),
    ]
