# Generated by Django 3.0.3 on 2020-03-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studycourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycourse',
            options={'verbose_name': 'student-购买的课程记录', 'verbose_name_plural': 'student-购买的课程记录'},
        ),
        migrations.AlterModelTable(
            name='studycourse',
            table='student-购买的课程记录',
        ),
    ]
