# Generated by Django 3.0.3 on 2020-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200320_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y-%m', verbose_name='课程的图片'),
        ),
    ]
