# Generated by Django 3.0.3 on 2020-03-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0033_auto_20200326_1636'),
        ('student', '0013_auto_20200325_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studycourse',
            unique_together={('course', 'account')},
        ),
    ]
