# Generated by Django 3.0.3 on 2020-03-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0012_userinfo_shop_cart_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='跟进内容')),
                ('date', models.DateField(auto_now_add=True, verbose_name='跟进日期')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='rbac.UserInfo', verbose_name='跟进学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='rbac.UserInfo', verbose_name='导师')),
            ],
            options={
                'verbose_name': 'teacher-学生跟进表',
                'verbose_name_plural': 'teacher-学生跟进表',
                'db_table': 'teacher-学生跟进表',
            },
        ),
    ]
