# Generated by Django 3.0.3 on 2020-03-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_auto_20200313_1232'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_stu', to='rbac.UserInfo', verbose_name='跟进学生'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_tea', to='rbac.UserInfo', verbose_name='导师'),
        ),
    ]
