# Generated by Django 3.0.3 on 2020-03-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_auto_20200313_1232'),
        ('teacher', '0002_auto_20200313_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='作业标题')),
                ('content', models.CharField(max_length=500, verbose_name='作业内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'teacher-作业表',
                'verbose_name_plural': 'teacher-作业表',
                'db_table': 'teacher-作业表',
            },
        ),
        migrations.CreateModel(
            name='HomeworkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/', verbose_name='作业文件')),
                ('homework_status', models.IntegerField(choices=[(1, '未提交'), (2, '已提交')], default=1, verbose_name='作业提交状态')),
                ('mark', models.PositiveIntegerField(blank=True, null=True, verbose_name='学生成绩')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Homework', verbose_name='作业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_stu', to='rbac.UserInfo', verbose_name='学生')),
            ],
            options={
                'verbose_name': 'teacher-作业提交记录表',
                'verbose_name_plural': 'teacher-作业提交记录表',
                'db_table': 'teacher-作业提交记录表',
            },
        ),
    ]
