# Generated by Django 3.0.3 on 2020-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_homework_homeworkrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkrecord',
            name='correction_file',
            field=models.FileField(blank=True, help_text='默认上传txt格式的文件', null=True, upload_to='correction/%Y-%m', verbose_name='批改过程'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/%Y-%m', verbose_name='作业文件'),
        ),
    ]
