# Generated by Django 3.0.3 on 2020-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studycourse'),
        ('teacher', '0005_auto_20200314_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='homeworkrecord',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='学生评价'),
        ),
    ]
