# Generated by Django 3.0.3 on 2020-03-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200320_1515'),
        ('teacher', '0006_auto_20200320_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.AddField(
            model_name='homework',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.CourseChapter', verbose_name='课程章节'),
        ),
    ]
