# Generated by Django 3.0.3 on 2020-03-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='一级菜单')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Icon', verbose_name='图标')),
            ],
        ),
    ]
