# Generated by Django 3.0.3 on 2020-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20200303_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmenu',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='一级菜单'),
        ),
    ]
