# Generated by Django 3.0.3 on 2020-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200303_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
