# Generated by Django 3.0.3 on 2020-03-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20200305_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='request_type',
        ),
        migrations.AddField(
            model_name='permission',
            name='firstmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.FirstMenu', verbose_name='一级菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='URL别名'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission'),
        ),
        migrations.AddField(
            model_name='permission',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='含正则的URL'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
