# Generated by Django 3.0.3 on 2020-03-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_permission_router_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmenu',
            name='icon',
        ),
    ]
