# Generated by Django 3.0.3 on 2020-03-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_remove_firstmenu_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.AlterModelOptions(
            name='firstmenu',
            options={'verbose_name': 'rbac-一级菜单表', 'verbose_name_plural': 'rbac-一级菜单表'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'rbac-权限表', 'verbose_name_plural': 'rbac-权限表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'rbac-角色表', 'verbose_name_plural': 'rbac-角色表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'rbac-用户表', 'verbose_name_plural': 'rbac-用户表'},
        ),
        migrations.AlterModelTable(
            name='firstmenu',
            table='rbac-一级菜单表',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='rbac-权限表',
        ),
        migrations.AlterModelTable(
            name='role',
            table='rbac-角色表',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='rbac-用户表',
        ),
    ]
