# Generated by Django 3.0.3 on 2020-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20200308_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='shop_cart_num',
            field=models.CharField(default=0, max_length=32, verbose_name='购物车商品数目'),
        ),
    ]
