# Generated by Django 3.0.3 on 2020-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_userinfo_shop_cart_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo'),
        ),
    ]
