# Generated by Django 3.0.3 on 2020-03-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_userinfo_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='student',
            new_name='students',
        ),
    ]
