# Generated by Django 3.0.3 on 2020-03-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_auto_20200313_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='students',
            new_name='student',
        ),
    ]
