# Generated by Django 3.0.3 on 2020-03-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0015_auto_20200313_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='student',
            new_name='teacher',
        ),
    ]
