# Generated by Django 3.0.3 on 2020-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0017_userinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(default=0, verbose_name='贝里余额'),
        ),
    ]
