# Generated by Django 3.0.3 on 2020-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_auto_20200320_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
