# Generated by Django 3.0.3 on 2020-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0020_auto_20200322_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='learning_process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学习进度'),
        ),
    ]
