# Generated by Django 3.0.3 on 2020-03-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0021_userinfo_learning_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='learning_process',
            new_name='learning_progress',
        ),
    ]
