# Generated by Django 3.0.3 on 2020-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0022_auto_20200323_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='component',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='组件名称'),
        ),
        migrations.AddField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='组件名称'),
        ),
    ]
