# Generated by Django 3.0.3 on 2020-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0023_auto_20200324_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='侧边栏是否出现'),
        ),
    ]
