# Generated by Django 3.0.3 on 2020-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0024_permission_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='router_name',
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='路由别名'),
        ),
    ]
