# Generated by Django 3.0.3 on 2020-03-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0025_auto_20200324_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='url',
            new_name='path',
        ),
    ]
