# Generated by Django 3.0.3 on 2020-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0026_auto_20200324_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='含正则的URL'),
        ),
        migrations.AddField(
            model_name='firstmenu',
            name='redirect',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='重定向的URL'),
        ),
    ]
