# Generated by Django 3.0.3 on 2020-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0027_auto_20200324_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='组件位置'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='侧边栏是否隐藏'),
        ),
    ]
