# Generated by Django 3.0.3 on 2020-03-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0029_apipermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipermission',
            name='method',
            field=models.IntegerField(choices=[(1, 'get'), (2, 'post'), (3, 'put'), (4, 'patch'), (5, 'delete')], default=1, verbose_name='请求方式'),
        ),
    ]
