# Generated by Django 3.0.3 on 2020-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0030_auto_20200326_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='api_permissions',
            field=models.ManyToManyField(to='rbac.ApiPermission', verbose_name='api权限'),
        ),
    ]
