# Generated by Django 3.0.3 on 2020-03-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0031_role_api_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apipermission',
            old_name='path',
            new_name='url',
        ),
    ]
