# Generated by Django 3.0.3 on 2020-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0032_auto_20200326_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipermission',
            name='method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE')], default=1, verbose_name='请求方式'),
        ),
    ]
